In [1]:
import numpy as np

# 1. Introducción a Numpy

Numpy (Numerical Python) es una librería de Python que se usa en ciencia de datos. Introduce el concepto de nparray, es una estructura de datos mucho más eficiente mucho más eficiente que las listas nativas de Python, sobre todo para trabajar con datos numéricos. No tiene puntero, no las recorre elemento a elemento, que es algo muy lento. 

## ¿Por qué NumPy en lugar de listas nativas?

Las listas nativas son flexibles pero muy lentas, se trabaja elemento a elemento. No están pensadas ni optimizadas para cálculos matemáticos. Numpy almacena datos siempre del mismo tipo (siempre numéricos). Permite operaciones vectorizadas, mucho más rápidas. 

In [26]:
import time #calcular tiempo

#sumar 1 millón de elementos de una lista en Python
lista = list(range(100))
inicio = time.time() #calcula el momento actual en segundos
resultado = [ x * 2 for x in lista] #cálculo con un bucle
print('tiempo', time.time() - inicio, resultado) #el momento final - el inicial me da el tiempo que ha tardado en ejecutarse

tiempo 0.011001110076904297 [0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182, 184, 186, 188, 190, 192, 194, 196, 198]


In [7]:
# La misma operación con numpy

array = np.arange(1_000_000)
inicio = time.time()
resultado = sum(array*2)
print('tiempo', time.time()-inicio, resultado)

tiempo 0.0827488899230957 999999000000


# El objeto ndarray

Un `ndarray` es un array N-dimensional de elementos del **mismo tipo**. A diferencia de una lista, todos sus elementos ocupan el mismo espacio en memoria, lo que permite operaciones vectorizadas sin bucles explícitos.

In [ ]:
np_lista = np.array([10,20.5,30,40,50])
lista = [1,2.5, 3, 4, 5]
print (lista) #una lista sale con los elementos separados por coma
print(np_lista) #una lista np es un array, desaparecen las comas
print(type(np_lista))
#puedo saber el tipo de todos los datos de mi array
print(np_lista.dtype) #todos los datos son float

np_dobles = np_lista * 2 #calcula el doble sin necesidad de bucle
print(np_dobles)

[1, 2.5, 3, 4, 5]
[10.  20.5 30.  40.  50. ]
<class 'numpy.ndarray'>
float64
[ 20.  41.  60.  80. 100.]


In [ ]:
booleanos = np.array([1,0,1,0,1,0], dtype= bool) #transforma un array de 1/0 a True/False
print(booleanos)
print(booleanos.dtype)

[ True False  True False  True False]
bool


# Creación de arrays con NumPy

NumPy ofrece múltiples formas de crear arrays, desde datos ya existentes(lista, tuplas, ficheros) o mediante funciones generadoras.

In [17]:
# Crear un vector de ceros
zero_vector = np.zeros((3)) #un vector con 3 0's
print (zero_vector)
print('='*10)

#Crear una matriz de ceros
zero_matriz = np.zeros((4,3)) #4 filas y 3 columnas
print(zero_matriz)
print('='*10)

#Crear una matriz de unos
matriz_unos = np.ones((2,3))
print(matriz_unos)
print('='*10)

#Crear matriz de cualquier valor
matriz_7 = np.full((3,3), 7) #matriz de 3x3 todas con 7
print(matriz_7)
print('='*10)

#Crear una matriz identidad
identidad = np.eye(4)
print(identidad)

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Creación de arrays aleatorios

Imprescindibles para hacer simulaciones, inicialización de pesos en machine learning, pruebas, etc.
Semilla o seed fija la aleatoriedad de los nºs dentro de mi array o vector, cuanto más grande sea el nº, mayor aleatoriedad. La semilla va de 0 a 100

In [24]:
#fijamos la semmilla
np.random.seed(50)#fija la aleatoriedad para obtener siempre los mismos valores
alturas = np.round(np.random.uniform(1.4, 2.16, size= 10),2) #genera un vector de distribución uniforme(1.4,2.16), el tercer parámetro es la longitud del vector
print(alturas)

[1.78 1.57 1.59 1.7  1.69 2.16 1.71 1.99 1.98 1.64]
