# Propiedades y estructuras

Antes de operar con un array, es fundamental saber cómo está organizado: cuántas dimensiones tiene, qué forma, cuántos elementos y de qué tipo. NumPy expone todos estos datos a través de atributos de ndarray. 

In [1]:
import numpy as np

In [ ]:
array = np.array([ [1,2,3],
                    [4,5,6],
                    [7,8,9],
                    [10,11,12]])
print(array)
print('dimension', array.shape)
print('nº de dimensiones de la matriz', array.ndim) #2 dimensiones, filas y columnas
print('tipo de dato de los elementos del array', array.dtype)
print('total de elementos', array.size) #filas * columnas

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
dimension (4, 3)
nº de dimensiones de la matriz 2
tipo de dato de los elementos del array int64
total de elementos 12


# Reshape: me permite cambiar la forma sin cambiar los datos

In [ ]:
vector = np.arange(12)
print(vector)

matriz = vector.reshape(3,4) #matriz de 3x4
print(matriz)
print('='*10)

matriz2 = vector.reshape(2,2,3)
print(matriz2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


# Vista vs Copia

In [ ]:
original = np.array([1,2,3,4,5,6,7])

vista = original.reshape(1,7) #vista depende por referencia de original, los cambios que se hagan sobre original afectan también a vista
copia = original.copy()

original[0] = 99 #afecta a original, es una vista no una copia

print(original)
print(vista)
print(copia)

# Otra forma de hacer una copia es a través del tipo
float = original.astype(np.float64) #lo copia cambiando el tipo
print(float)

[99  2  3  4  5  6  7]
[[99  2  3  4  5  6  7]]
[1 2 3 4 5 6 7]
[99.  2.  3.  4.  5.  6.  7.]
