# Manipulación de arrays

En el trabajo real los datos no siempre llegan en el formato esperado o necesitado. A veces tenemos que **unir** o **dividir** los datos en partes. Y también **ordenarlos**

In [1]:
import numpy as np

## Concatenar arrays: unir dos o más arrays en uno solo

Concatenar dos listas

In [3]:
grupo_manana = np.array(['Lucía', 'Marta', 'Rodrigo'])
grupo_tarde  = np.array(['Juan', 'Lara', 'David'])

todos = np.concatenate([grupo_manana, grupo_tarde]) #el orden es importante, los concatena siguiendo ese orde
print(grupo_manana)
print(grupo_tarde)
print(todos)

['Lucía' 'Marta' 'Rodrigo']
['Juan' 'Lara' 'David']
['Lucía' 'Marta' 'Rodrigo' 'Juan' 'Lara' 'David']


En arrays 2D (tablas) tienes dos opciones:
- Pegar **por debajo** (añadir filas): como añadir nuevas filas a una tabla
- Pegar **por la derecha** (añadir columnas): como añadir nuevas columnas a una tabla

```
Pegar por debajo (axis=0):      Pegar por la derecha (axis=1):

[1, 2]          [1, 2, 5, 6]
[3, 4]  +        →
[5, 6]          [3, 4, 7, 8]
[7, 8]
```

# Concatenar tablas de 2D
# imagina que tienes las notas de clase por aula

clase_A = np.arra

In [ ]:
# Concatenar tablas de 2D
# imagina que tienes las notas de clase por aula

clase_A = np.array([ #doble corchete porque es una matriz
    [6,7,8], #alumno 1 de A
    [2,7,4]
]) 

clase_B =  np.array([
    [8,6,8], #alumno 1 de B
    [4,9,6],
    [7,7,5]
])

#poner todas las notas de las dos clases juntas es pegar hacia abajo --> axis = 0
todas_las_clases = np.concatenate([clase_A, clase_B], axis=0)
print(todas_las_clases)
print('dimension array resultante, 5 alumnos, 3 asignaturas:', todas_las_clases.shape)


[[6 7 8]
 [2 7 4]
 [8 6 8]
 [4 9 6]
 [7 7 5]]
dimension array resultante, 5 alumnos, 3 asignaturas:  (5, 3)


In [10]:
# Imagina que tienes las notas por asignatura
notas_mates = np.array([ [6], [7], [10] ]) #3 alumnos, será 1 columna
notas_ingles = np.array([ [2], [4] , [7] ]) 
notas_ciencias = np.array([ [2], [4] , [7] ])

# axis = 1 añadir por columnas poner una al lado de la otra
tabla = np.concatenate([notas_mates, notas_ingles, notas_ciencias], axis=1)
print(tabla)


[[ 6  2  2]
 [ 7  4  4]
 [10  7  7]]


## vstack y hstack atajos de apilación

vstack => vertical
hstack => horizontal

```
vstack  →  apila en vertical (uno encima del otro):
           [1, 2, 3]        [[1, 2, 3],
           [4, 5, 6]   →    [4, 5, 6]]

hstack  →  apila en horizontal (uno al lado del otro):
           [1, 2] y [3, 4]  →  [1, 2, 3, 4]
```


In [13]:
primer_trimestre = np.array([7,6,5,4,3,2,1])
segundo_trimestre = np.array([1,3,5,7,9,11,13])

# vstack los vectores pasan a ser filas de la matriz
notas_2_trimestres = np.vstack([primer_trimestre, segundo_trimestre])
print(notas_2_trimestres)
print(notas_2_trimestres.shape, '2 trimestres 7 alumnos')

# hstack los vectores se concatenan un vector con todas las notas.
todo_junto = np.hstack([primer_trimestre, segundo_trimestre])
print(todo_junto)

[[ 7  6  5  4  3  2  1]
 [ 1  3  5  7  9 11 13]]
(2, 7) 2 trimestres 7 alumnos
[ 7  6  5  4  3  2  1  1  3  5  7  9 11 13]


## Dividir arrays: la operación inversa a concatenar
Dividir es lo contrario de concatenar: **partir un array en trozos**.

```
Array original: [10, 20, 30, 40, 50, 60]

Dividido en 3 partes iguales:
  Parte 1: [10, 20]
  Parte 2: [30, 40]
  Parte 3: [50, 60]
```

También puedes indicar **en qué posiciones** se hacen los cortes:

```
Array: [10, 20, 30, 40, 50, 60, 70, 80]
Cortes en posición 3 y 6:
         [10, 20, 30] | [40, 50, 60] | [70, 80]
                       ↑             ↑
                    pos 3           pos 6
```


In [17]:
notas_todos = np.array([6.5 ,4.3,7 ,1.5 ,0 ,9 ,10 ,7.5 ,8 ,8.7 ,4, 5])

# dividir en 4 grupos iguales(divisible exacto)
grupo1, grupo2, grupo3, grupo4 = np.split(notas_todos, 4)
print(grupo1)
print(grupo2)
print(grupo3)
print(grupo4)
print('='*15)
# dividir en posiciones específicas 
inicio, medio, fin = np.split(notas_todos, [4,8]) #la posición 4 (elemento 0 de la lista) es la de corte, es decir, 0 es el primer elemento del segundo grupo
print(inicio)
print(medio)
print(fin)

[6.5 4.3 7. ]
[1.5 0.  9. ]
[10.   7.5  8. ]
[8.7 4.  5. ]
[6.5 4.3 7.  1.5]
[ 0.   9.  10.   7.5]
[8.  8.7 4.  5. ]


## vsplit y hsplit: vsplit separa en filas y hsplit separa en columnas

In [20]:
#tenemos una matriz y queremos separar por vectores

tabla = np.array([ #las filas serían alumnos, las columnas serían las asignaturas
    [6,7,8,9],
    [5,7,9,1],
    [2,4,6,8],
    [0,7,5,3]
    ])

# 2 parejas de alumnos dos clases, vsplit

print('VSPLIT en la vertical')
clase_a, clase_b = np.vsplit(tabla,2)
print(clase_a)
print('-'* 30)
print(clase_b)

print("#" * 30)

# 2 asignaturas por bloque

print('HSPLIT en la horizontal')
asignatura_a, asignatura_b = np.hsplit(tabla,2)
print(asignatura_a)
print('-'* 30)
print(asignatura_b)

VSPLIT en la vertical
[[6 7 8 9]
 [5 7 9 1]]
------------------------------
[[2 4 6 8]
 [0 7 5 3]]
##############################
HSPLIT en la horizontal
[[6 7]
 [5 7]
 [2 4]
 [0 7]]
------------------------------
[[8 9]
 [9 1]
 [6 8]
 [5 3]]


## Ordenación: np.sort y no.argsort

np.sort: ordena los valores
Ordena el valor de los elementos 

```
Datos:   [7, 2, 9, 1, 5, 3]
Ordenado:[1, 2, 3, 5, 7, 9]  ← de menor a mayor
```
np.argsort: ordena los indices

No devuelve los valores ordenados, sino **las posiciones** donde estarían en orden. Es muy útil cuando tienes dos arrays relacionados (p.ej. nombres y notas) y quieres ordenar uno según el otro.

```
Datos:    [7,  2,  9,  1,  5,  3]
Posición:  0   1   2   3   4   5

argsort:  [3,  1,  5,  4,  0,  2]
           ↑   ↑   ↑   ↑   ↑   ↑
         pos  pos pos pos pos pos
          del  del del del del del
          más pequeño          más grande



In [ ]:
nombres = np.array(['Ana', 'Luis', 'Eva', 'Carlos', 'Marta', 'Pedro'])
notas = np.array([7.2, 6.1, 8.8 ,5.5 , 2.0, 7.5])

print('Datos originales')
for n, nota in zip(nombres, notas):
    print(f'{n:9s}:{nota}') #nombre lo pongo con 9 espacios para que quede alineada la visualización

Datos originales
Ana      :7.2
Luis     :6.1
Eva      :8.8
Carlos   :5.5
Marta    :2.0
Pedro    :7.5


In [ ]:
# np.sort: solo ordena las notas

notas_ordenadas_desc = np.sort(notas, descending=False)
print(notas_ordenadas_desc)

#Quiero ordenar el array de nombres en función del orden notas --> argsot
#Quiero el ranking de peor a mejor nota

orden = np.argsort(notas)

for posicion, idx in enumerate(orden, start=1): #hará una enumeración del orden empezando en 1. En este caso hay seis elementos, idx va de 1 a 6 .
        print(f'{posicion}º - {nombres[idx]}: {notas[idx]}')     

''' #este bucle hace lo mismo
   for o, alumnos in zip(orden, nombres): 
    print( nombres[o] )
'''              

[2.  5.5 6.1 7.2 7.5 8.8]
1º - Marta: 2.0
2º - Carlos: 5.5
3º - Luis: 6.1
4º - Ana: 7.2
5º - Pedro: 7.5
6º - Eva: 8.8


## Valores únicos: np.unique

Devuelve los valores que aparecen en el array eliminando los repetios, y tambien me dice cuantas veces se repita cada valor

In [25]:
# Ejemplo: respuestas a una encuesta de satisfacción (1 a 5 estrellas)
respuestas = np.array([3, 2, 1, 2, 2, 5, 3, 2, 3, 5, 2, 4])

# valores unicos
print(np.unique(respuestas))

# frecuencia de cada valor
puntuacion, conteo = np.unique(respuestas, return_counts=True)
print(puntuacion, conteo)

print('Resultado de mi encuesta: ')
for p, c in zip(puntuacion, conteo):
    barra = "★" * c
    print( f"{p} estrella: {c} respuesta {barra}" )


[1 2 3 4 5]
[1 2 3 4 5] [1 5 3 1 2]
Resultado de mi encuesta: 
1 estrella: 1 respuesta ★
2 estrella: 5 respuesta ★★★★★
3 estrella: 3 respuesta ★★★
4 estrella: 1 respuesta ★
5 estrella: 2 respuesta ★★


In [26]:
# Si en el ejercicio anterior queremos ordenar por número de votaciones 
# valores unicos
print(np.unique(respuestas))

# frecuencia de cada valor
puntuacion, conteo = np.unique(respuestas, return_counts=True)

indices_ordenados = np.argsort(conteo, descending=True)

print('Resultado de mi encuesta: ')
# for p, c in zip(puntuacion, conteo):
#     barra = "★" * c
#     print( f"{p} estrella: {c} respuesta {barra}" )

for i in indices_ordenados:
    c = conteo[i]
    p = puntuacion[i]
    barra = "★" * c
    print( f"{p} estrella: {c} respuesta {barra}" )



[1 2 3 4 5]
Resultado de mi encuesta: 
2 estrella: 5 respuesta ★★★★★
3 estrella: 3 respuesta ★★★
5 estrella: 2 respuesta ★★
1 estrella: 1 respuesta ★
4 estrella: 1 respuesta ★


---
**Resumen del tema:**

| Operación | Función | Qué hace |
|-----------|---------|----------|
| Unir en serie | `np.concatenate([a, b])` | Pega arrays uno tras otro |
| Apilar filas | `np.vstack([a, b])` | Pone b debajo de a (añade filas) |
| Apilar columnas | `np.hstack([a, b])` | Pone b a la derecha de a (añade columnas) |
| Dividir en N partes | `np.split(a, N)` | Divide en N partes iguales |
| Dividir en posiciones | `np.split(a, [i, j])` | Cortes en índices i y j |
| Dividir por filas | `np.vsplit(a, N)` | Parte la tabla horizontalmente |
| Dividir por columnas | `np.hsplit(a, N)` | Parte la tabla verticalmente |
| Ordenar valores | `np.sort(a)` | Devuelve copia ordenada |
| Índices de orden | `np.argsort(a)` | Devuelve posiciones para ordenar |
| Eliminar repetidos | `np.unique(a)` | Valores distintos (+ conteo opcional) |